import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import I18nProvider from '@/components/Utils/Component/I18nProvider/I18nProvider'
// import { useTranslation } from 'next-i18next'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    // const { i18n } = useTranslation()
    // lang={i18n.language}
    return (
        <html>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <I18nProvider>
                    <Header />
                    {children}
                    <Footer />
                </I18nProvider>
            </body>
        </html>
    )
}
